### ISSUE TITLE
TCP Brutal Configuration Options

### ISSUE THREAD

**Issue by Sortnz** [chika0801/sing-box-examples#105]
1. I would like to inquire about the simultaneous use of the `"flow": "xtls-rprx-vision"` configuration alongside the `"brutal": {"enabled": true}` setting. It appears that these two configurations cannot coexist, and I am curious to know the underlying reason for this limitation. Is there a technical conflict that prevents their concurrent operation, or is it a design choice?

2. I am comparing the `"flow": "xtls-rprx-vision"` with the `"padding": true` setting to evaluate if they offer similar levels of performance in anti-censorship scenarios. Could you please provide insights into whether these two configurations yield comparable results, or if one is recommended over the other under certain conditions?

**Comment by chika0801** [comment]
> I would like to inquire about the simultaneous use of the "flow": "xtls-rprx-vision" configuration alongside the "brutal": {"enabled": true} setting. It appears that these two configurations cannot coexist, and I am curious to know the underlying reason for this limitation. Is there a technical conflict that prevents their concurrent operation, or is it a design choice?

I think it's VISION that can't be interoperable with TCP Mux type in terms of code technology.

As for the code I don't know enough to answer you more about why.

> I am comparing the "flow": "xtls-rprx-vision" with the "padding": true setting to evaluate if they offer similar levels of performance in anti-censorship scenarios. Could you please provide insights into whether these two configurations yield comparable results, or if one is recommended over the other under certain conditions?

That question, when I first saw the Mux author in sing-box add padding, I too wondered which was better, or how they were the same and different.

I don't understand code principles, so I can't help you with this question.

Since VISION is used in Xray to handle TLS in TLS issues. Assuming that this check is applied in your national firewall. how much does padding in Mux also work, my observation is that there is not a definitive study (e.g., a published formal report) on either side of the fence, sing-box or xray.

Maybe these controversial experimental data will be published, when the cybersecurity researchers at whichever university, will publish it.

This kind of public research, maybe this site can help you https://gfw.report/
