### ISSUE TITLE
Long time no see. Master

### ISSUE THREAD

**Issue by Thaomtam** [chika0801/sing-box-examples#127]
I want to ask about hysteria2 singbox.I configured correctly and the server runs. but when the client connects to port 443, there is no connection At first I thought it was an error, so then I added trojan 443, and it worked.But hysteria2 443 does not. Master has instructions to help me explain. Thanks master

**Comment by chika0801** [comment]
I can't tell what the problem is after reading the phenomenon you described.

If you confirm that hy2 is on the server side and the client side, the corresponding parameters are filled correctly. But the client just can't connect successfully.

Then using the method of exclusion test, you find another VPS, the configuration file remains unchanged, and see if you can successfully connect on another VPS. This is a troubleshooting method.
